--liquibase formatted sql

--changeset DATA:001
insert into DRONES (id, serial_number, model, weight_limit, battery_capacity, state) values
((NEXT VALUE FOR DRONES_SEQUENCE), 'NX-01',      'LIGHTWEIGHT',   100, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-1701',   'MIDDLEWEIGHT',  200, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-74656',  'CRUISERWEIGHT', 300, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-75567',  'HEAVYWEIGHT',   400, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-1701-D', 'HEAVYWEIGHT',   500, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-1764',   'LIGHTWEIGHT',   100, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-57580',  'MIDDLEWEIGHT',  200, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-76725',  'CRUISERWEIGHT', 300, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-75306',  'MIDDLEWEIGHT',  200, 100, 'IDLE'),
((NEXT VALUE FOR DRONES_SEQUENCE), 'NCC-82893',  'HEAVYWEIGHT',   500, 100, 'IDLE');
--rollback delete from drones;

--changeset DATA:002
insert into MEDICATIONS (id, name, weight, code, image) values
((NEXT VALUE FOR MEDICATIONS_SEQUENCE), 'ACETAMINOPHEN',    50,  '100', 'tylenol.png'),
((NEXT VALUE FOR MEDICATIONS_SEQUENCE), 'RAD-X',            200, '101', 'rad-x.png'),
((NEXT VALUE FOR MEDICATIONS_SEQUENCE), 'RAD-AWAY',         250, '102', 'rad-away.png'),
((NEXT VALUE FOR MEDICATIONS_SEQUENCE), 'COVID-19 VACCINE', 150, '103', 'astrazenka.png'),
((NEXT VALUE FOR MEDICATIONS_SEQUENCE), 'CHLORHEXIDINE',    100, '104', 'Chlorhexidine.png');